### ISSUE TITLE
README and basic documentation

### ISSUE THREAD

**Issue by mwlon** [mulimoen/rust-blosc-src#12]
This crate is great, and seems to be the most easily usable Blosc crate available. However, it looks pretty sketchy, and that almost scared me away from trying it. A README and some basic documentation would go a long way to make it friendlier-looking.

**Comment by mulimoen** [comment]
Thank you for appreciating this crate @mwlon. I have created #13 which I hope is something along the lines of what you are looking for

**Comment by mwlon** [comment]
Yep, that's a good start. A code example in the REAMDE and a few doc comments (`/// stuff`) on the most important functions and constants would be great too, if you get a chance!
